# Generated by Django 3.0.5 on 2021-01-22 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=58)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=58)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=50)),
                ('aceptada', models.BooleanField(default=False)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_valoracion', to='producto.Producto')),
            ],
        ),
    ]
